#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | install-clients.yml' 
  hosts: localhost 
  vars_files:
    #- 'vars/vault.yml'
    - 'vars/container-build.yml'
    - 'vars/clients.yml'
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "install-clients"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"

  pre_tasks:

  tasks:
    - name: '{{ ansible_name_module }} | Download Clients if necessary'
      when:
        - download_clients is defined
        - download_clients | bool
        - clients is defined 
        - clients.items is defined 
        - clients.items() | length > 0 
      block:
        - name: '{{ ansible_name_module }} | Set Client packages download destination'
          ansible.builtin.set_fact:
            client_staging: "/tmp/clients"
          when:
            - not client_staging is defined or client_staging == ''

        - name: '{{ ansible_name_module }} | Ensure Client packages download destination exists'
          ansible.builtin.file:
            path: "{{ client_staging }}"
            state: directory
            mode: '0755'

        - ansible.builtin.debug:
            msg:
              - "{{ item.value.url }}{{ (item.value.pkg_version + '/') if item.value.pkg_version is defined and item.value.pkg_version != '' else ''}}{{ item.value.pkg_name }}{{ item.value.pkg_suffix }}"
              - "{{ client_staging }}/{{ item.value.pkg_name }}{{ item.value.pkg_extention }}"
          with_dict: "{{ clients }}"

        - name: '{{ ansible_name_module }} | Download binaries'
          ansible.builtin.get_url:
            url: "{{ item.value.url }}{{ (item.value.pkg_version + '/') if item.value.pkg_version is defined and item.value.pkg_version != '' else ''}}{{ item.value.pkg_name }}{{ item.value.pkg_suffix }}"
            dest: "{{ client_staging }}/{{ item.value.pkg_name_short }}{{ item.value.pkg_extention }}"
          with_dict:
            - "{{ clients }}"
          when:
            - download_clients is defined
            - download_clients | bool 
            - not download_local is defined or not download_local | bool

        - name: '{{ ansible_name_module }} | Download binaries from local repository'
          ansible.builtin.get_url:
            url: "{{ item.value.localurl }}{{ item.value.pkg_name }}{{ item.value.localpkg_suffix }}"
            dest: "{{ client_staging }}/{{ item.value.pkg_name_short }}{{ item.value.pkg_extention }}"
            url_username: "{{ registry_admin_username }}"
            url_password: "{{ registry_admin_password }}"
            force_basic_auth: 'true'
            validate_certs: 'true'
            client_cert: ''
          with_dict:
            - "{{ clients }}"
          when:
            - download_clients is defined
            - download_clients | bool 
            - download_local is defined
            - download_local | bool

    - name: '{{ ansible_name_module }} | Install Clients if necessary'
      when:
        - install_clients is defined
        - install_clients | bool 
      block:
        - name: '{{ ansible_name_module }} | Ensure aws staging destination exists'
          become: true
          ansible.builtin.file:
            path: "{{ aws_staging_dir }}"
            state: directory
            mode: '0755'

        - name: '{{ ansible_name_module }} | extract aws archive '
          ansible.builtin.shell: |
            unzip -o {{ client_staging }}/{{ clients['awscliv2'].pkg_name_short }}{{ clients['awscliv2'].pkg_extention }} -d {{ aws_staging_dir }}
          register: aws_bin_out

        - name: '{{ ansible_name_module }} | print extracted aws archive output'
          ansible.builtin.debug:
            var: aws_bin_out
            verbosity: 2

        - name: '{{ ansible_name_module }} | install aws bin'
          become: yes
          ansible.builtin.shell: >
            bash {{ aws_staging_dir }}/aws/install --update -b /usr/bin
          register: aws_bin_install_out

        - name: '{{ ansible_name_module }} | print installed aws archive output'
          ansible.builtin.debug:
            var: aws_bin_install_out
            verbosity: 2

        - name: '{{ ansible_name_module }} | list installed aws bin'
          become: yes
          ansible.builtin.shell: >
            ls -l /usr/bin | grep aws
          register: aws_bin_list_out

        - name: '{{ ansible_name_module }} | print installed aws archive list output'
          ansible.builtin.debug:
            var: aws_bin_list_out
            verbosity: 2

        - name: '{{ ansible_name_module }} | chmod installed aws archive'
          become: true
          ansible.builtin.shell: >
            chmod a+x /usr/bin/aws
          when:
            - aws_bin_install_out is defined
            - aws_bin_install_out.rc is defined
            - aws_bin_install_out.rc == 0
            - aws_bin_install_out.stdout is defined
            - aws_bin_install_out.stdout != ''
            - "'/usr/bin/aws' in aws_bin_install_out.stdout"

        - name: '{{ ansible_name_module }} | install tar archive'
          become: true
          ansible.builtin.shell: | 
            tar xzvf {{ client_staging }}/{{ item.value.pkg_name_short }}{{ item.value.pkg_extention }} -C /usr/bin/
          when:
            - "'tar.gz' in item.value.pkg_extention" 
          with_dict:
            - "{{ clients }}"
          register: clients_tar_installed 

        - name: '{{ ansible_name_module }} | print  tar archive install output 1 of 2'
          ansible.builtin.debug:
            var: clients_tar_installed
            verbosity: 2
              
        - name: '{{ ansible_name_module }} | print tar archive install output 2 of 2'
          ansible.builtin.debug:
            var: item 
            verbosity: 2
          loop: "{{ clients_tar_installed.results }}"
              
        - name: '{{ ansible_name_module }} | install zip archive'
          become: true
          ansible.builtin.shell: | 
            unzip -o -f -u {{ client_staging }}/{{ item.value.pkg_name_short }}{{ item.value.pkg_extention }} -d /usr/bin
          when:
            - "'.zip' in item.value.pkg_extention" 
            - "not 'aws' in item.value.pkg_name_short"
          with_dict:
            - "{{ clients }}"
          register: clients_zip_installed 

        - name: '{{ ansible_name_module }} | print  zip archive install output 1 of 2'
          ansible.builtin.debug:
            var: clients_zip_installed
            verbosity: 2
              
        - name: '{{ ansible_name_module }} | print zip archive install output 2 of 2'
          ansible.builtin.debug:
            var: item 
            verbosity: 2
          loop: "{{ clients_zip_installed.results }}"
              
        - name: '{{ ansible_name_module }} | find installed helm bin'
          become: true
          ansible.builtin.shell: > 
            ls -l /usr/bin | grep helm | awk '{print $9}'
          register: helm_bin_out 

        - name: '{{ ansible_name_module }} | rename installed helm bin'
          become: true
          ansible.builtin.shell: > 
            mv -f /usr/bin/{{ item }} /usr/bin/helm
          loop: "{{ helm_bin_out.stdout_lines }}"
          when:
            - helm_bin_out is defined
            - helm_bin_out.rc is defined
            - helm_bin_out.rc == 0
            - helm_bin_out.stdout_lines is defined
            - helm_bin_out.stdout_lines | length > 0 
            - item != 'helm'

        - name: '{{ ansible_name_module }} | list of  installed binaries '
          become: true
          ansible.builtin.shell: | 
            ls -l /usr/bin | awk '{print $9}' | egrep -i "{{ binary_cli_search_list |join('|') }}"
          register: clients_bin_out 

        - name: '{{ ansible_name_module }} | print  zip archive install output 1 of 2'
          ansible.builtin.debug:
            var: clients_bin_out 
            verbosity: 2
              
        - name: '{{ ansible_name_module }} | chmod installed oc archive'
          become: true
          ansible.builtin.shell: | 
            chmod a+x /usr/bin/oc
          when:
            - "'oc' in clients_zip_installed.results"

        - name: '{{ ansible_name_module }} | chmod installed tar archive'
          become: true
          ansible.builtin.shell: | 
            chmod a+x /usr/bin/{{ item }}
          loop: "{{ clients_bin_out.stdout_lines }}" 
          register: clients_tar_chmoded 

        - name: '{{ ansible_name_module }} | Ensure aws staging destination does not exists'
          become: true
          ansible.builtin.file:
            path: "{{ aws_staging_dir }}"
            state: absent 
            mode: '0755'
