---
roles:
  - name: MindPointGroup.rhel8_stig
  - name: MindPointGroup.rhel9_stig
collections:
  - name: amazon.aws
  - name: amazon.cloud
  - name: awx.awx
  - name: ansible.security
  - name: ansible.controller
  - name: ansible.hub
  - name: ansible.network
  - name: ansible.utils
  - name: ansible.posix
  - name: ansible.netcommon
  - name: cloud.terraform
  - name: community.crypto
  - name: community.general
  - name: community.vmware
  - name: containers.podman
  - name: kubernetes.core
  - name: redhat.openshift
  - name: redhat_cop.controller_configuration

